# Ingestion Layer runs on port 8081
server.port=8081

# PostgreSQL connection — SUPABASE
spring.datasource.url=jdbc:postgresql://db.qcnhzndyptepoadjaldd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=dsj3mjhncWPBf9s7
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ollama base URL
ollama.base-url=http://localhost:11434

# Max file upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
