# Feedback Layer runs on port 8084
server.port=8084

# PostgreSQL connection — SUPABASE
spring.datasource.url=jdbc:postgresql://db.qcnhzndyptepoadjaldd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=dsj3mjhncWPBf9s7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
